name: entregables

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest  # Cambié a ubuntu-latest, es más común para Python
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.2'

      - name: Create virtual environment
        run: python -m venv venv

      - name: Activate virtual environment & install dependencies
        shell: bash
        run: |
          source venv/bin/activate  # Cambié a venv/bin/activate para Ubuntu
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install requests  # Asegura que 'requests' esté instalado

      - name: Run actividad_1
        shell: bash
        run: |
          source venv/bin/activate && python src/pad20251/actividad_1.py

      - name: Run actividad_2
        shell: bash
        run: |
          source venv/bin/activate && python src/pad20251/actividad_2.py

      - name: Run actividad_3
        shell: bash
        run: |
          source venv/bin/activate && python src/pad20251/actividad_3.py

      - name: Run proyecto_integrador  # Agregado este paso
        shell: bash
        run: |
          source venv/bin/activate && python src/pad20251/proyecto_integrador.py

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: entregable actualizado
          commit_user_name: Luis de la Ossa [GitHub Actions]
          commit_user_email: fernando.delaossa@est.iudigital.edu.co
          commit_author: Luis de la Ossa <fernando.delaossa@est.iudigital.edu.co>